### ISSUE TITLE
Agent name forced translated with the timespan translator

### ISSUE THREAD

**Issue by haloivanid** [EisFrei/ingress-prime-stats-to-json#1] opened 2022-11-06 03:09 UTC
Hi, I think it's the first issue in this repository, and didn't see any rules on how to report some issues. I will clear as possible.
The bug is when any agent names that some word of it is related to the timespan translation value it will force converted. Like, agent "NURI" converts to "NOWRI", etc.

**Comment by EisFrei** [comment] 2022-11-06 12:40
Thanks for bringing this to my attention.
The issue is fixed in version 0.1.0

**Closed as completed** 2022-11-06 12:41 UTC
